#!/bin/zsh

# Identify and display the Ethernet interface characteristics:
#   (a) Identify broadcast address

ifconfig en0 | grep broadcast | awk '{print $6}'

# en0 is active ethernet connection ???
# some output manipulation to get only the address