#!/bin/bash

# In what file can you find the installed version of your Debian?

cat /etc/debian_version

# alternatively we can use `cat /etc/os-release`
# alternatively we can use `cat /etc/issue`
# alternatively we can use `lsb_release -a`
# alternatively we can use `hostnamectl`

# all these alternative methods don't give us the exact
# version and / or contain a lot of additional information
