#!/bin/bash

# What command can you use to rename your system?

hostname new_hostname

# it affects only the transient hostname

# alternatively we can use `hostnamectl set-hostname new_hostname`
# it affects both static and transient hostnames
