#!/bin/bash

# What file has to be modified to make it permanent?

echo /etc/hostname

# changes will be seen through `hostname` only after rebooting the system

# alternatively we can use `hostnamectl set-hostname new_hostname`
# changes will be seen through `hostname` immediately
