#!/bin/bash

# Name the command that displays the available space left
# and used on the system in an humanly understandable way

df -h

# -h option for human-readable output (powers of 2)
# -H option for human-readable output (powers of 10)
