#!/bin/bash

# Figure out the exact size of each folder of /var in a
# humanly understandable way followed by the path of it

du -sh /var/*

# -s option displays only a total for each argument
# -h option for human-readable output
