#!/bin/bash

# Three’s a Charm. Write a script of you choice

if [ $# -lt 1 ] ; then
  echo "usage: $(basename "$0") files_to_extract"
  exit 1
fi

extract () {
  for arg in "$@" ; do
    if [ -f "$arg" ] ; then
      case "$arg" in
        *.tar.bz2)  tar -xvjf "$arg"  ;;
        *.tar.gz)   tar -xvzf "$arg"  ;;
        *.tar.xz)   tar -xvJf "$arg"  ;;
        *.bz2)      bunzip2 "$arg"    ;;
        *.gz)       gunzip "$arg"     ;;
        *.tar)      tar -xf "$arg"    ;;
        *.tbz2)     tar -xjf "$arg"   ;;
        *.tgz)      tar -xzf "$arg"   ;;
        *.zip)      unzip "$arg"      ;;
        *.Z)        uncompress "$arg" ;;
        *.rar)      rar -x "$arg"     ;;
        *.jar)      jar -xvf "$arg"   ;;
        *)          echo "'$arg' cannot be extracted with this script" ;;
      esac
    else
      echo "'$arg' is not a valid file!"
    fi
  done
}

extract "$@"

# Extract all your files with one script!
